services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - job-flow
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - job-flow
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    networks:
      - job-flow
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin1234"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - job-flow
  user-service:
    image: bigboyjuicer/jobflow-user-service
    env_file:
      - docker-env
    ports:
      - "8080:8080"
    networks:
      - job-flow
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
networks:
  job-flow:
    name: jobflow
    external: true