spring.application.name=vacancy-service
server.port=8081
server.servlet.context-path=/api/v1

#Additional config
spring.config.import=file:../.env[.properties]

#PostgreSQL Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=${DB_VACANCY_SCHEMA}
spring.jpa.show-sql=true

#Liquibase
spring.liquibase.enabled=true
spring.liquibase.default-schema=${DB_VACANCY_SCHEMA}