spring.application.name=user-service
spring.profiles.active=dev
server.servlet.context-path=/api/v1

#Additional config
#spring.config.import=optional:file:D:/job-flow/.env[.properties]

#PostgreSQL Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=${DB_USER_SCHEMA}

#Liquibase
spring.liquibase.enabled=true
spring.liquibase.default-schema=${DB_USER_SCHEMA}

#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}